### PR TITLE
Handle props and URL params in MapsIndoorsMap component

### PR DESCRIPTION
**Pull request by ammapspeople**
# What

Refactor the handling of props and query parameters to be the responsibility of the MapsIndoorsMap component.

### CODE REVIEW

**Review by andreeaceachir142 — APPROVED** [review]
✅

**Comment by andreeaceachir142** [comment]
There are still some places where we use `hasURLParameters` on the MapTemplate.jsx file. Do we still need that, or can we get rid of it completely on that file?

**Comment by andreeaceachir142** [comment]
Do we need all the props defined on the MapsIndoorsMap.jsx component, or is it enough to have them on the MapTemplate.jsx?

**Comment by ammapspeople** [comment]
> Do we need all the props defined on the MapsIndoorsMap.jsx component, or is it enough to have them on the MapTemplate.jsx?

The MapsIndoorsMap is the "public facing" component (and web component), so it needs to be there and passed down to the child component, MapTemplate. Or am I misunderstanding? Can you elaborate?

**Comment by andreeaceachir142** [comment]
> > Do we need all the props defined on the MapsIndoorsMap.jsx component, or is it enough to have them on the MapTemplate.jsx?
> 
> The MapsIndoorsMap is the "public facing" component (and web component), so it needs to be there and passed down to the child component, MapTemplate. Or am I misunderstanding? Can you elaborate?

The same props are defined on the MapTemplate and also on the MapsIndoorsMap files - and I thought they don't need to be present in both files, but it makes sense that they need to exist on the public facing component and web component too. 

image

**Comment by ammapspeople** [comment]
> There are still some places where we use `hasURLParameters` on the MapTemplate.jsx file. Do we still need that, or can we get rid of it completely on that file?

It was my ambition to only have that in the MapsIndoorsMap component. I'll look into it.

**Comment by ammapspeople** [comment]
@andreeaceachir142 I removed the unnecessary hasURLParameters from the MapTemplate component now.

**Pull request merged**
